services:
  gemini-converter-adapter:
    build: .
    container_name: gemini-converter-adapter
    restart: always
    ports:
      - "8100:8100"
    env_file:
      - ./.env
    volumes:
      # Use a named volume for logs
      - logs_data:/app/logs
      # Mount the entire project directory to /data for easy access if needed
      - .:/data

# Define the named volume at the top level
volumes:
  logs_data:
