services:
  gemini-converter-adapter:
    build: .
    container_name: gemini-converter-adapter
    restart: always
    ports:
      - "8000:8100"  # Map external 8000 to internal 8100
    env_file:
      - ./.env
    volumes:
      # Use a named volume for logs
      - logs_data:/app/logs
      # Mount the entire project directory to /data for easy access if needed
      - .:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8100

# Define the named volume at the top level
volumes:
  logs_data:
