version: '3.8'

services:
  gemini-claude-adapter:
    build: .
    container_name: gemini-claude-adapter
    restart: always
    ports:
      # 将主机的 8000 端口映射到容器的 8000 端口
      # 这样可以避免与主机上可能运行的其他服务（如Nginx）发生端口冲突
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      # Mount the logs directory
      - ./logs:/app/logs
      # Mount the entire project directory to /data with write permissions
      - .:/data
    # Run as root for script execution (allows writing files)
    user: "0:0"